# Generated by Django 4.0.1 on 2022-04-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('methode', models.CharField(choices=[('OrangeMoney', 'OM'), ('Wave', 'WAVE'), ('Livraison', 'LIVRAISON'), ('Carte', 'CARTE')], max_length=20, verbose_name='Methode de paiement')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('paiement_effectue', models.BooleanField(default=True)),
                ('total_paye', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_commande',),
            },
        ),
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_elements', to='boutique.produit')),
            ],
        ),
    ]
