# Generated by Django 4.0.1 on 2022-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=250, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_complet',
            field=models.CharField(max_length=50, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='paiement_effectue',
            field=models.BooleanField(default=True, verbose_name='Paiement effectué'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='telephone',
            field=models.CharField(max_length=100, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total_paye',
            field=models.IntegerField(verbose_name='Total à payer'),
        ),
        migrations.AlterField(
            model_name='produitcommande',
            name='prix',
            field=models.IntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produitcommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
