# Generated by Django 4.0.1 on 2022-04-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='boutique.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='contributeurs',
            field=models.ManyToManyField(related_name='contributeur', through='boutique.ContributeurLivre', to='boutique.Contributeur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='editeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.editeur'),
        ),
        migrations.AddField(
            model_name='contributeurlivre',
            name='contributeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.contributeur'),
        ),
        migrations.AddField(
            model_name='contributeurlivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre', to='boutique.produit'),
        ),
    ]
