# Generated by Django 4.0.1 on 2022-04-22 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='in_user_souhait',
            field=models.ManyToManyField(blank=True, related_name='user_souhait', to=settings.AUTH_USER_MODEL),
        ),
    ]
