# Generated by Django 4.0.1 on 2022-04-22 17:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='addresse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='modifie',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pays de résidence'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='prenoms',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom utilisateur'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='ville',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ville'),
        ),
    ]
