# Generated by Django 4.0.1 on 2022-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_userbase_addresse_alter_userbase_modifie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='cree',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='modifie',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modifié le'),
        ),
    ]
